# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Simplicity is the eloquence of art
description: >- # this means to ignore newlines until "baseurl:"
  Architecte logiciels orienté Java, j'ai toujours souhaité avoir mon propre blog pour diffuser des informations au plus grand nombre.
  Que vous soyez informaticien ou simple curieux, j'espère que le contenu vous plaira et que vous y trouverez les informations que vous cherchez.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cedricsarre.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  cedricSarre
author: Cédric Sarre
aMonPropos: |-
  Architecte logiciels orienté Java, je suis passionné par les nouvelles technologies que je teste (PoC), que j'analyse et que je présente ensuite à d'autres collaborateurs. <br>
  J'aime suivre des conférences telles que le Devoxx France, le Spring One, les webinar ElasticSearch, les BreizhJUG… <br>
  J'apporte mes compétences Java en réalisant des audits de code pour différents clients. <br>
  Je participe activement aux avant-ventes qui me sont proposées.<br>
  J'imagine les futures architectures logicielles qui correspondent au mieux aux attentes clients. <br>
  Je participe aux entretiens techniques en vue de renforcer les équipes de développements. C’est aussi un moyen pour moi de comprendre la mise en place de certaines solutions et d’apprendre. <br>
  Je partage mes acquis avec les équipes via des formations, des retours d’expérience ou des présentations de PoC. <br>
  A mon sens, un architecte logiciels se doit de faire de la veille technologique, d’être curieux, enthousiaste, de partager activement, et d’avoir de bonnes connaissances dans les différentes solutions d'hébergement (SAAS, PAAS, IAAS…) et dans les différents types d'architecture (Microservices, Hexagonale, Event-Driven, Monolithe Modulaire...) ; et ceci afin de réaliser des architectures logicielles les plus modernes, maintenables, durables et résilientes que possible.<br>

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
